Acumulado Mês Histórico =



VAR Escolha = SELECTEDVALUE('Tipo de Exibição Históricos'[Valor])

RETURN
    SWITCH(
        Escolha,
        0, SUM('Faturamento e Devoluções Histórico (DQ)'[D2_VRLIQ]) - SUM('Faturamento e Devoluções Histórico (DQ)'[D1_VRLIQ]),
        
        1, SUM('Faturamento e Devoluções Histórico (DQ)'[D2_QUANT]) - (SUM('Faturamento e Devoluções Histórico (DQ)'[D1_QUANT]))
    )