

SELECT AD1_FILIAL,
	   AD1_NROPOR,
	   AD1_DTINI, AD1_DTFIM,
	   AD1_CODCLI, AD1_NREDUZ,
	   AD1_CODPRO, AD1_DESCRI, B1_MCCATEG, B1_GRUPO, B1_DESCGRP,
	   AD1_VEND, A3_NOME,
	   
	   AD1_STATUS,
	   CASE
		WHEN AD1_STATUS = '1' THEN 'ABERTO'
		WHEN AD1_STATUS = '2' THEN 'REPROVADO'
		WHEN AD1_STATUS = '3' THEN 'SUSPENSO'
		WHEN AD1_STATUS = '4' THEN 'APROVADO'
		WHEN AD1_STATUS = '6' THEN 'AMOSTRA ENVIADA'
		WHEN AD1_STATUS = '7' THEN 'AGUARDANDO APROVACAO'
		WHEN AD1_STATUS = '9' THEN 'VENDA REALIZADA'
	   END AS 'STATUS',

	   AD1_PROVEN,
	   
	   AD1_STAGE,
	   CASE
		WHEN AD1_STAGE = '000001' AND AD1_PROVEN = '002' THEN 'CONTROLE DE RESULTADO DA AMOSTRA'
		WHEN AD1_STAGE = '000002' AND AD1_PROVEN = '002' THEN 'ANALISE DE CREDITO'
		WHEN AD1_STAGE = '000003' AND AD1_PROVEN = '002' THEN 'VENDA REALIZADA'
	   END AS ESTAGIO

FROM AD1010

LEFT JOIN SA3010 ON AD1_VEND = A3_COD
JOIN SB1010 ON AD1_CODPRO = B1_COD AND AD1_FILIAL = B1_FILIAL

WHERE
	AD1_PROVEN = '002'
AND AD1010.D_E_L_E_T_ = ''
AND SA3010.D_E_L_E_T_ = ''
AND SB1010.D_E_L_E_T_ = ''

