
--Saldo de Produtos 

SELECT B1_TIPO,B2_FILIAL, B2_COD, B1_DESC, B1_MCCATEG, 
	
		CASE
			WHEN B1_MCCATEG = '1' THEN 'PIGMENTOS'
			WHEN B1_MCCATEG = '2' THEN 'OXIDOS'
			WHEN B1_MCCATEG = '3' THEN 'POS-METÁLICOS'
			WHEN B1_MCCATEG = '4' THEN 'DISPERSÃO'
			WHEN B1_MCCATEG = '5' THEN 'REVENDA'
		END AS CATEG,

B1_CI, B1_GRUPO, B1_DESCGRP, B2_LOCAL, B2_QATU, B2_QPEDVEN, (B2_QATU - B2_QPEDVEN) AS QDISP

FROM SB2010 , SB1010

WHERE B2_FILIAL <> '02'
	  AND B1_FILIAL = B2_FILIAL 
	  AND B2_COD = B1_COD
	  AND B1_GRUPO BETWEEN '1000' AND '5999'
	  AND B1_TIPO = 'PA'
	  AND B2_LOCAL = '06'
	  AND SB1010.D_E_L_E_T_ = ''
	  AND SB2010.D_E_L_E_T_ = ''


