
-- Metas de Vendas do Mês

SELECT  BM_DESC, 
		CT_DATA, CT_DESCRI, CT_FILIAL, CT_GRUPO, CT_MOEDA, CT_QUANT, CT_VALOR, CT_VEND, CAST(CT_CATEGO AS INT) AS CT_CATEGO

FROM SCT010 ,SBM010

WHERE 
LEFT(CT_DATA, 6) = FORMAT(GETDATE(), 'yyyyMM')
AND CT_GRUPO = BM_GRUPO
AND SCT010.D_E_L_E_T_ = ''
AND SBM010.D_E_L_E_T_ = ''


