
--Saldo de Produtos 

SELECT B2_FILIAL, B2_COD, B8_LOTECTL, B1_DESC, B1_MCCATEG,
	
		CASE
			WHEN B1_MCCATEG = '1' THEN 'PIGMENTOS'
			WHEN B1_MCCATEG = '2' THEN 'OXIDOS'
			WHEN B1_MCCATEG = '3' THEN 'POS-METÁLICOS'
			WHEN B1_MCCATEG = '4' THEN 'DISPERSÃO'
			WHEN B1_MCCATEG = '5' THEN 'REVENDA'
		END AS CATEG,

B1_CI, B1_GRUPO, B1_DESCGRP, B8_SALDO, B2_CM1, B8_DATA, B8_SDMOV,

	CASE
		--WHEN B8_SDMOV = '' THEN DATEDIFF( DAY, CONVERT(DATE, STUFF(STUFF(B8_DATA, 5, 0, '-'), 8, 0, '-')), GETDATE() )
		WHEN B8_SDMOV <> '' THEN DATEDIFF( DAY, CONVERT(DATE, STUFF(STUFF(B8_SDMOV, 5, 0, '-'), 8, 0, '-')), GETDATE() )

	END AS DIAS_ULTMOV,

--VALOR = B2_CM1 * B8_SALDO,
VALOR = ROUND(B2_CM1 * B8_SALDO, 2),

B2_LOCAL

FROM SB2010, SB1010, SB8010

WHERE B2_FILIAL <> '02'
	  AND B1_FILIAL = B2_FILIAL
	  AND B2_COD = B1_COD
	  AND B2_FILIAL = B8_FILIAL
	  AND B8_PRODUTO = B2_COD
	  AND B1_GRUPO BETWEEN '1000' AND '5999'
	  AND B2_QATU > '0'
	  AND B8_SALDO > '0'
	  AND B2_COD = B8_PRODUTO
	  AND B2_FILIAL = B8_FILIAL
	  AND B2_LOCAL = B8_LOCAL

	  AND SB1010.D_E_L_E_T_ = ''
	  AND SB2010.D_E_L_E_T_ = ''
	  AND SB8010.D_E_L_E_T_ = ''